/*
 * Copyright (c) StreetHawk, All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

import Foundation

class InstallViewController: StreetHawkBaseTableViewController
{
    var arrayValues : [NSArray] = [] //cells for value displaying on the table
    var arrayDescriptions : [NSArray] = [] //cells for description displaying on the table
    
    //life cycle
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        
        let arrayGeneralDescription : NSMutableArray = []
        arrayGeneralDescription.addObject("The unique installation ID for the device. Generated by StreetHawk SDK automatically. If delete and re-install, install id changes.")
        arrayGeneralDescription.addObject("Customer developer register app_key in streethawk server. It's same as `StreetHawk.appKey`.")
        arrayGeneralDescription.addObject("Your unique identifier for this Client. Tagged by API `SHApp.sharedInstance().tagCuid(<unique_value>)`")
        arrayGeneralDescription.addObject("The version of the client application.")
        arrayGeneralDescription.addObject("The version of StreetHawkCore framework SDK.")
        arrayGeneralDescription.addObject("Operate system and version.")
        arrayGeneralDescription.addObject("If this App is AppStore or Enterprise provisioning profile, it's true; otherwise it's false.")
        arrayGeneralDescription.addObject("Development platform, hardcoded in StreetHawk SDK.")
        arrayGeneralDescription.addObject("The UTC time this install was created in year-month-day hour:minute:second format.")
        arrayGeneralDescription.addObject("The UTC time this install was modified in year-month-day hour:minute:second format.")
        arrayGeneralDescription.addObject("If current App deleted and re-install again, install id changes. This property is the Install this Install has been replaced by.")
        arrayGeneralDescription.addObject("An estimated timestamp (UTC) when the Install has been uninstalled, nil otherwise.")
        let arrayGeneralValue = NSMutableArray(capacity: arrayGeneralDescription.count)
        let arrayCapabilityDescription : NSMutableArray = []
        arrayCapabilityDescription.addObject("Customer developer uses location related SDK functions, technically when his pod include `streethawk/Locations` or `streethawk/Geofence` or `streethawk/Beacons` and set `StreetHawk.isLocationServiceEnabled = YES` this is true; otherwise this is false.")
        arrayCapabilityDescription.addObject("Customer developer uses notification related SDK functions, technically when his pod include `streethawk/Push` and set `StreetHawk.isNotificationEnabled = YES` this is true; otherwise this is false.")
        arrayCapabilityDescription.addObject("Customer developer uses iBeacon related SDK functions, technically when his pod include `streethawk/Beacons` this is true; otherwise this is false.")
        arrayCapabilityDescription.addObject("When `featureiBeacons == YES` and end user's device supports iBeacon (iOS version >= 7.0, location service enabled and bluetooth enabled), it's true.")
        let arrayCapabilityValue = NSMutableArray(capacity: arrayCapabilityDescription.count)
        let arrayPushDescription : NSMutableArray = []
        arrayPushDescription.addObject("If iOS App use development provisioning, it's `dev`; if use simulator, it's `simulator`; if use ad-hoc or AppStore or Enterprise distribution provisioning, it's `prod`.")
        arrayPushDescription.addObject("The access data for remote notification.")
        arrayPushDescription.addObject("It set to time stamp once get error from Apple's push notification server. If empty means Apple not reply error.")
        arrayPushDescription.addObject("Timestamp when end user refuse to receive notification. If notification is approved it's empty.")
        arrayPushDescription.addObject("Whether use \"smart push\".")
        arrayPushDescription.addObject("Timestamp for feed. If not nil and local fetch time is older than this, SDK will fetch feed.")
        let arrayPushValue = NSMutableArray(capacity: arrayPushDescription.count)
        let arrayDeviceDescription : NSMutableArray = []
        arrayDeviceDescription.addObject("Device's location. StreetHawk server try to guess location by ip even when device disable location, thus it may not be nil even device disable location.")
        arrayDeviceDescription.addObject("UTC offset in minutes.")
        arrayDeviceDescription.addObject("Raw text for the device model, e.g. `iPhone 8.1`.")
        arrayDeviceDescription.addObject("Ip address of current device. It's known by server, not sent from client.")
        arrayDeviceDescription.addObject("Mac address sent to server by client. It's not available since iOS 7 device, which always returns 02:00:00:00:00:00.")
        arrayDeviceDescription.addObject("[UIDevice device].identifierForVendor, a way to identifier vendor.")
        arrayDeviceDescription.addObject("If customer developer pass in advertise identifier, submit to StreetHawk server. It requires App to approve IDFA when submitting to AppStore, thus StreetHawk SDK cannot positively read this property. Set up by `StreetHawk.advertisingIdentifier = ...`.")
        arrayDeviceDescription.addObject("Carrier of current device.")
        arrayDeviceDescription.addObject("Screen resolution of current device.")
        let arrayDeviceValue = NSMutableArray(capacity: arrayDeviceDescription.count)
        self.arrayValues = [arrayGeneralValue, arrayCapabilityValue, arrayPushValue, arrayDeviceValue];
        self.arrayDescriptions = [arrayGeneralDescription, arrayCapabilityDescription, arrayPushDescription, arrayDeviceDescription];
        
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(self.a(_:)), name: SHInstallRegistrationSuccessNotification, object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(self.a(_:)), name: SHInstallUpdateSuccessNotification, object: nil)

    }
    
    override init(style: UITableViewStyle)
    {
        super.init(style: .Grouped)
    }
    
    func a(notification: NSNotification)  {
        
    }
}